### ISSUE TITLE
nccl test only gets ～65% of the link bandwidth

### ISSUE THREAD

**Issue by sandyhouse** [NVIDIA/nccl-tests#112]
Environment:

2 nodes with A100 GPUs intra-connected with PCIe Gen 4 and NVLink, inter-connected with four 200Gb RoCEv2 NICs.
NCCL version is: 2.11.4
CUDA version is: 11.6
The result of ib_write_bw is about 180Gb
GPU Topo:
![image](https://user-images.githubusercontent.com/6737864/177527291-4ac1736f-08e9-44b1-ab95-2f0c3c1a4c6a.png)

nccl-tests command:
```
mpirun -np 16 -H host1:8,host2:8 -bind-to none -map-by slot -x NCCL_TOPO_DUMP_FILE=$PWD/topology.xml -x LD_LIBRARY_PATH -x PATH -x NCCL_IB_GID_INDEX=3 -x NCCL_IB_HCA=mlx5_0 -mca btl_tcp_if_include ens10np0 -mca pml ob1 -mca btl ^openib --allow-run-as-root ./build/all_reduce_perf -b 1G -e 8G -f 2
```
![image](https://user-images.githubusercontent.com/6737864/177528349-df51dc9c-9c89-443f-ac98-d4fdcaa0c5d3.png)

As the result shows, the average bus bandwidth is only 9.84 GB/s (about 80Gbps), which is far away from the link bandwidth.

Any suggestions?

**Comment by sjeaugey** [comment]
Can you attach the topology file you generated with `NCCL_TOPO_DUMP_FILE=$PWD/topology.xml`?

**Comment by sjeaugey** [comment]
So, with 4 NICs you would get ~40 GB/s?

Did you make sure ACS was disabled? That could explain why bandwidth is halved.

**Comment by sandyhouse** [comment]
> ACS

Thanks for your reply. The ACS is enabled on my machines and I'll disable the function and have a retry.

**Comment by sandyhouse** [comment]
> So, with 4 NICs you would get ~40 GB/s?
> 
> Did you make sure ACS was disabled? That could explain why bandwidth is halved.

Now I disabled I/O virtualization and ACS. But the bus bandwidth is only 20.78GB (~166Gbps vs 200Gbps NIC), is this right?
![image](https://user-images.githubusercontent.com/6737864/178184427-1dbe20a0-de2c-46d8-82a6-19f7175dbfed.png)

**Comment by sandyhouse** [comment]
Additionally, When I use two NICs, I can get about 41GBps bus bandwidth. But when I use four NICs, I only get 41GBps bus bandwidth. Any idea?

**Comment by sjeaugey** [comment]
20GB/s per NIC is not uncommon on RoCE, especially if you didn't bump the MTU to 9000.

For the 4 NIC problem, can you dump the topology again, this time running with all 4 NICs and all 8 GPUs? I can only see one NIC in the previous topology.

**Comment by sjeaugey** [comment]
Seems like GPU Direct RDMA is missing. That's why you don't get 4x the performance but only 2x. That could also explain the not-ideal performance. GPU Direct was there in the first topology file though so I guess it was just an oversight after rebooting.
