### ISSUE TITLE
NCCL failure common.cu:916 

### ISSUE THREAD

**Issue by gmyofustc** [NVIDIA/nccl-tests#15]
I use mpi to lanch multi-node nccl test, it gives me this error info
![image](https://user-images.githubusercontent.com/7859276/45751127-fb50b000-bc43-11e8-9ccd-b2b2921a09de.png)

But I am able to lanch local node nccl test like this
![image](https://user-images.githubusercontent.com/7859276/45751193-39e66a80-bc44-11e8-937d-434889dcdfc0.png)

how can I fix this. Many Tanks

**Comment by sjeaugey** [comment]
Hi, you try adding `-x NCCL_DEBUG=WARN` to your mpirun arguments to get a precise message from NCCL explaining the "unhandled system error".

**Comment by sjeaugey** [comment]
Oops clicked the wrong button -- reopening.

**Comment by yrsun** [comment]
I am facing the same issue. I cannot figure this out. Please help.

**Comment by AddyLaddy** [comment]
Can you try and get more diagnostics by launching with;

mpirun -x NCCL_DEBUG=WARN

or

mpirun -x NCCL_DEBUG=INFO

**Comment by yrsun** [comment]
I have two servers, and each has at least two gpus.

When I try to launch the test from server2, with NCCL_DEBUG=WARN, it shows the following information:
My command is: mpirun -x NCCL_DEBUG=WARN -np 2 -npernode 1 --hostfile hostfile ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 1 -c 0

Connecting to socket xxx.xxx.xxx.x<46012>

server1:6601:6625 [0] include/socket.h:385 NCCL WARN Net : Connection closed by remote peer
NCCL failure common.cu:921 'unhandled system error'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[9614,1],0]
  Exit code:    1
--------------------------------------------------------------------------
[server2:05612] 1 more process has sent help message help-mpi-btl-openib-cpc-base.txt / no cpcs for port
[server2:05612] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages


With NCCL_DEBUG=INFO, it shows the following message:
server1:7693:7741 [0] NCCL INFO CUDA Dev 0, IB Ports : mlx5_0/1(PHB) 

server1:7693:7741 [0] include/socket.h:385 NCCL WARN Net : Connection closed by remote peer
server1:7693:7741 [0] NCCL INFO transport/net_socket.cu:188 -> 2
server1:7693:7741 [0] NCCL INFO bootstrap.cu:39 -> 2
server1:7693:7741 [0] NCCL INFO bootstrap.cu:255 -> 2
server1:7693:7741 [0] NCCL INFO init.cu:428 -> 2
server1:7693:7741 [0] NCCL INFO init.cu:562 -> 2
server1:7693:7741 [0] NCCL INFO misc/group.cu:69 -> 2 [Async thread]
NCCL failure common.cu:921 'unhandled system error'
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[10131,1],0]
  Exit code:    1
--------------------------------------------------------------------------


In my nccl-test/src/common.cu:921 in server1, this line is: NCCLCHECK(ncclGroupEnd()); in the following codes. I just add some printf sentences, so the line number changes a little bit.
  //if parallel init is not selected, use main thread to initialize NCCL
  ncclComm_t* comms = (ncclComm_t*)malloc(sizeof(ncclComm_t)*nThreads*nGpus);
  if (!parallel_init) {
     if (nProcs == 1) {
       int gpuArray[nGpus*nThreads];
       for (int i=0; i<nGpus*nThreads; i++) gpuArray[i] = i;
       NCCLCHECK(ncclCommInitAll(comms, nGpus*nThreads, gpuArray));
     } else {
       NCCLCHECK(ncclGroupStart());
       for (int i=0; i<nGpus*nThreads; i++) {
         CUDACHECK(cudaSetDevice(localRank*nThreads*nGpus+i));
         NCCLCHECK(ncclCommInitRank(comms+i, nProcs*nThreads*nGpus, ncclId, proc*nThreads*nGpus+i));
       }
       **NCCLCHECK(ncclGroupEnd());**
     }

     for (int p=0; p<nProcs; p++) {
       if (p == proc) {
         for (int i=0; i<nThreads*nGpus; i++) {
           int cudaDev;
           int rank;
           cudaDeviceProp prop;
           NCCLCHECK(ncclCommCuDevice(comms[i], &cudaDev));
           NCCLCHECK(ncclCommUserRank(comms[i], &rank));
           CUDACHECK(cudaGetDeviceProperties(&prop, cudaDev));
           fflush(stdout);
         }
       }
#ifdef MPI_SUPPORT
       MPI_Barrier(MPI_COMM_WORLD);
#endif
       fflush(stdout);
     }
  }

**Comment by yrsun** [comment]
My team figured out solution of my problem.

we have env variable added to the top of ~/.bashrc:
export NCCL_SOCKET_IFNAME=xxx

we changed our command line to:
mpirun -x LD_LIBRARY_PATH=$PWD/../build/lib -np 2 --hostfile hostfile ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 1 -c 0

I hope this solution can help you too.

**Comment by acgtyrant** [comment]
I met the similiar error too, see: https://discuss.pytorch.org/t/nccl-error-in-torch-c-dist-broadcast-tensor-src-group-when-train-in-two-nodes/28787

**Comment by acgtyrant** [comment]
@yrsun What does `xxx` mean in `export NCCL_SOCKET_IFNAME=xxx`? What does `LD_LIBRARY_PATH=$PWD/../build/lib` do? Thank you!

**Comment by sjeaugey** [comment]
@acgtyrant  In many cases, you need to tell NCCL which IP interface to use because NCCL cannot know which one is functional between the nodes. So for example, set `NCCL_SOCKET_IFNAME=enp3s0` in the case you linked.

Setting LD_LIBRARY_PATH was only a way to force the usage of the NCCL library which had been built on the side(in  $PWD/../build/lib).

**Comment by acgtyrant** [comment]
@sjeaugey Why do you build the NCCL library on the side? Is it neccessary to solve the problem?

**Comment by acgtyrant** [comment]
I export the `NCCL_SOCKET_IFNAME`, but it still time out:

```
gpu-bql-144-103:18553:18553 [0] INFO NET : Using interface enp3s0:192.168.144.103<0>
gpu-bql-144-103:18553:18553 [0] INFO NET/IB : Using interface enp3s0 for sideband communication
gpu-bql-144-103:18553:18553 [0] INFO Using internal Network Socket
gpu-bql-144-103:18553:18553 [0] INFO Using NCCL Low-latency algorithm for sizes below 16384
gpu-bql-144-103:18553:18553 [0] INFO NET : Using interface enp3s0:192.168.144.103<0>
gpu-bql-144-103:18553:18553 [0] INFO NET/Socket : 1 interfaces found
NCCL version 2.2.13+cuda9.0
gpu-bql-144-103:18553:18612 [0] INFO comm 0x7fa42c00a3b0 rank 0 nranks 2

gpu-bql-144-103:18553:18611 [0] include/socket.h:360 WARN Call to connect failed : Connection timed out
gpu-bql-144-103:18553:18611 [0] INFO transport/net_socket.cu:118 -> 2
gpu-bql-144-103:18553:18611 [0] INFO bootstrap.cu:28 -> 2 [Net]
gpu-bql-144-103:18553:18611 [0] INFO bootstrap.cu:119 -> 2 [bthread]

gpu-bql-144-103:18553:18612 [0] include/socket.h:371 WARN Connection closed by remote peer
gpu-bql-144-103:18553:18612 [0] INFO transport/net_socket.cu:166 -> 2
gpu-bql-144-103:18553:18612 [0] INFO bootstrap.cu:45 -> 2 [Net]
gpu-bql-144-103:18553:18612 [0] INFO bootstrap.cu:259 -> 2
gpu-bql-144-103:18553:18612 [0] INFO init.cu:413 -> 2
gpu-bql-144-103:18553:18612 [0] INFO init.cu:536 -> 2
gpu-bql-144-103:18553:18612 [0] INFO misc/group.cu:70 -> 2 [Async thread]
Traceback (most recent call last):
  File "train.py", line 285, in <module>
    main()
  File "train.py", line 243, in main
    model, device_ids=[local_rank], output_device=local_rank)
  File "/mapbar/data/home/acgtyrant/Projects/drn/.env/lib/python3.5/site-packages/torch/nn/parallel/distributed.py", line 150, in __init__
    self.broadcast_bucket_size)
  File "/mapbar/data/home/acgtyrant/Projects/drn/.env/lib/python3.5/site-packages/torch/nn/parallel/distributed.py", line 264, in _dist_broadcast_coalesced
    dist._dist_broadcast_coalesced(self.process_group, tensors, buffer_size)
RuntimeError: NCCL error in: /pytorch/torch/lib/c10d/ProcessGroupNCCL.cpp:271, unhandled system error
```

**Comment by acgtyrant** [comment]
@sjeaugey Is it neccessary that all nodes's NCCL_SOCKET_IFNAME must be same name?

**Comment by AddyLaddy** [comment]
Maybe you could also try setting; NCCL_SOCKET_IFNAME=^docker
This will ensure that NCCL doesn't try and use the Docker network interface if you're running inside a container?

**Comment by AddyLaddy** [comment]
Maybe you could also try setting; NCCL_SOCKET_IFNAME=^docker
This will ensure that NCCL doesn't try and use the Docker network interface if you're running inside a container?

**Comment by AddyLaddy** [comment]
Closing old issues. Please open another one if you are still seeing issues.
