### ISSUE TITLE
what do algobw actually mean when I run test with more than one nodes?speed between nodes or speed between gpus.

### ISSUE THREAD

**Issue by wenjunlong** [NVIDIA/nccl-tests#160]
I have four nodes, the hardware for each node is like 

![image](https://github.com/NVIDIA/nccl-tests/assets/7665366/140ad481-2d81-4b4c-b066-294c4baa5c3a)

and 
![image](https://github.com/NVIDIA/nccl-tests/assets/7665366/0e4a62d7-a755-4487-8a9c-3fabfd9f0535)

when I run the test, the best result with algobw I've ever got was around 90GB/s (with two nodes) , and 80GB/s  (with four nodes), which is aproximate the expected speed between nodes in a peer-to-peer form. then when I ran the test within one node, the result was also around 90GB/s.

So could you please tell me if they are reasonable result ? and what does algobw really  mean in all these circumstance。Thank you!

**Comment by sjeaugey** [comment]
On 2 nodes, it depends which algorithm is used. If we use tree, the performance will be limited by a mix of NVLink and NIC bandwidth so it's not reflecting physical speeds. If we use ring, the busbw is going to reflect exactly what's going through the NICs.

On 3+ nodes we should use rings for large enough sizes, so the 80 GB/s is probably reflecting the total NIC bandwidth, hence 20GB/s per NIC which is not 24 (what we see ourselves in general on perfect setups) but not too bad either. Also note, you need to use large enough sizes as to see the real peak bandwidth. You didn't share the NCCL perf tests output so I can't tell whether you've reached the peak or not. If you do, please run from 8 bytes to 8 GB (`-b 8 -e 8G -f 2`).

**Comment by wenjunlong** [comment]
Sorry for the lack of information. those GPUs are A800，Communication speed between GPUs inside one node is 400GB/s.  I also want to apologize for an error message provided earlier, the numbers I provided were  actually busbw 
.       
the  command I used was:

/usr/mpi/gcc/openmpi-4.1.5rc2/bin/mpirun --allow-run-as-root --report-bindings -host $HOSTS -np $NP --bind-to numa -mca coll_hcoll_enable 0 -mca pml ucx -mca pml_ucx_verbose 0 -x CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7" -x NCCL_IB_HCA=$MLX5_DEVICES -x NCCL_SOCKET_IFNAME=ens22f0 -x NCCL_DEBUG=INFO -x NCCL_ALGO=Tree -x LD_LIBRARY_PATH=/root/nccl-2.18.3-1/build/lib:/usr/mpi/gcc/openmpi-4.1.5rc2/lib:/usr/local/cuda/lib64/  /root/nccl-tests-2.13.6/build/all_reduce_perf -b 8 -e 4096M -f 2 -g 1

the output were like 

![image](https://github.com/NVIDIA/nccl-tests/assets/7665366/54ac9785-6468-483e-b22a-8a6023c87882)

for 2 nodes , and 

![image](https://github.com/NVIDIA/nccl-tests/assets/7665366/cd7255b5-ca62-4bdf-85b2-bbeeeb0c7452)

for 4 nodes

These test were conducted serval days ago, and I haven't  got a chance to try another one these days.

Thank you for your advice, I will have another try when I get a chance.

But before that, May I ask for your advice regarding the corrected information?

**Comment by wenjunlong** [comment]
> On 2 nodes, it depends which algorithm is used. If we use tree, the performance will be limited by a mix of NVLink and NIC bandwidth so it's not reflecting physical speeds. If we use ring, the busbw is going to reflect exactly what's going through the NICs.
> 
> On 3+ nodes we should use rings for large enough sizes, so the 80 GB/s is probably reflecting the total NIC bandwidth, hence 20GB/s per NIC which is not 24 (what we see ourselves in general on perfect setups) but not too bad either. Also note, you need to use large enough sizes as to see the real peak bandwidth. You didn't share the NCCL perf tests output so I can't tell whether you've reached the peak or not. If you do, please run from 8 bytes to 8 GB (`-b 8 -e 8G -f 2`).

Sorry for the lack of information. those GPUs are A800，Communication speed between GPUs inside one node is 400GB/s.  I also want to apologize for an error message provided earlier, the numbers I provided were  actually busbw .       
the  command I used was:

/usr/mpi/gcc/openmpi-4.1.5rc2/bin/mpirun --allow-run-as-root --report-bindings -host $HOSTS -np $NP --bind-to numa -mca coll_hcoll_enable 0 -mca pml ucx -mca pml_ucx_verbose 0 -x CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7" -x NCCL_IB_HCA=$MLX5_DEVICES -x NCCL_SOCKET_IFNAME=ens22f0 -x NCCL_DEBUG=INFO -x NCCL_ALGO=Tree -x LD_LIBRARY_PATH=/root/nccl-2.18.3-1/build/lib:/usr/mpi/gcc/openmpi-4.1.5rc2/lib:/usr/local/cuda/lib64/  /root/nccl-tests-2.13.6/build/all_reduce_perf -b 8 -e 4096M -f 2 -g 1

the output were like 

![image](https://github.com/NVIDIA/nccl-tests/assets/7665366/54ac9785-6468-483e-b22a-8a6023c87882)

for 2 nodes , and 

![image](https://github.com/NVIDIA/nccl-tests/assets/7665366/cd7255b5-ca62-4bdf-85b2-bbeeeb0c7452)

for 4 nodes

These test were conducted serval days ago, and I haven't  got a chance to try another one these days.

Thank you for your advice, I will have another try when I get a chance.

But before that, May I ask for your advice regarding the corrected information?

**Comment by sjeaugey** [comment]
Ok, thanks. So indeed the peak BW is a bit lower than I'd expect. Maybe it would be worth checking with the networking support team that the NIC firmwares are upgraded to the latest and correctly tuned.
