### ISSUE TITLE
misc/ibvwrap.cc:278 NCCL WARN Call to ibv_reg_mr_iova2 failed with error Cannot allocate memory

### ISSUE THREAD

**Issue by jxh314** [NVIDIA/nccl-tests#206]
Hello, when I run the following command to disable shm on a single node in order to force the use of ib for testing, I encounter the following error:
<img width="1388" alt="image" src="https://github.com/NVIDIA/nccl-tests/assets/59605941/eda16b13-8c85-4a18-9831-d6cc91f25114">
Modifying the /etc/security/limits.conf configuration file as referenced in https://docs.nvidia.com/deeplearning/nccl/archives/nccl_2143/user-guide/docs/troubleshooting.html#infiniband
also does not take effect.
The log, topo and graph file are as follows:

- [single.log](https://github.com/NVIDIA/nccl-tests/files/15022442/single.log)

- [dump_topo.txt](https://github.com/NVIDIA/nccl-tests/files/15022452/dump_topo.txt)

- [dump_graph.txt](https://github.com/NVIDIA/nccl-tests/files/15022455/dump_graph.txt)
 
By the way, the perftest is ok. Can you help with that?

**Comment by sjeaugey** [comment]
Modifying `/etc/security/limits.conf` is the long term solution so that limits are good on the next reboot. Did you reboot? Did you ensure ulimit -l was indeed showing the right values, even within `mpirun`?

You can ensure that running `mpirun <mpirun args> <some script printing ulimit -l>`

**Comment by jxh314** [comment]
Thanks a lot, it works! 
before setting this，  the result of `ulimit -l ` was only 8192.
