### ISSUE TITLE
How busbw numbers relate to network utilization?

### ISSUE THREAD

**Issue by yaroslavvb** [NVIDIA/nccl-tests#22]
I'm seeing 125 Gbps reported by `all_reduce_perf` ([log](https://app.wandb.ai/yaroslavvb/nccl_bench/runs/c2d4w4di/logs)) which is surprising because AWS EFA network is advertised to be only 100 Gbps.

Does this mean 100 Gbps advertised limit is being exceeded? If not, how do I figure out the  busbw achievable by `all_reduce_perf` on a 100 Gbps net?

**Comment by AddyLaddy** [comment]
Due to the nature of the NCCL tree algorithm the reported BusBW figure can exceed the actual available peak BW, when running on just 2 nodes.
See Sylvain's comment here; https://github.com/NVIDIA/nccl/issues/209#issuecomment-498745923

You can disable the tree algorithm with `NCCL_TREE_THRESHOLD=0` and that should give more accurate BusBW numbers.

**Comment by yaroslavvb** [comment]
Ah I see. If I switch to ring, bus bandwidth is now 60Gbps, but performance is much worse.
IE 1GB allreduce time goes from 134ms to [268ms](https://app.wandb.ai/yaroslavvb/nccl_bench/runs/h88z6t5h/logs)

**Comment by AddyLaddy** [comment]
You may be able to achieve higher BW on EFA enabled instances by using this experimental patch; https://github.com/aws/aws-ofi-nccl/commit/2806caf377972c2cfef11fbd7961abb668699042

**Comment by yaroslavvb** [comment]
Those numbers are actually with the patch. However, instructions I got from AWS only worked when evaluating with nccl 2.6. Upgrading to 2.7 I'm getting bogged in dependency hell, not sure if I should expect much difference from 2.7

**Comment by AddyLaddy** [comment]
I have measured up to 10GB/s BusBW with the NCCL tests. My command line included these parameters; `/home/ec2-user/anaconda3/bin/mpirun -x FI_PROVIDER="efa" -x FI_OFI_RXR_RX_COPY_UNEXP=1 -x FI_OFI_RXR_RX_COPY_OOO=1 -x FI_EFA_MR_CACHE_ENABLE=1 -x FI_OFI_RXR_INLINE_MR_ENABLE=1`

**Comment by yaroslavvb** [comment]
Updating this discussion here
https://github.com/NVIDIA/nccl/issues/235
