### ISSUE TITLE
Getting Avg bus bandwidth = 0 when running all_reduce_perf in nccl-tests in my EC2 G5.8x large

### ISSUE THREAD

**Issue by rajeshvenkata** [NVIDIA/nccl-tests#249]
I am trying to run nccl test in single g5.8xlarge and it always gives Avg bus bandwidth = 0. It works in more than 1 node for g5.8xlarge. It works for single p4d.24xlarge node as well. This issue happens for only single g5.8xlarge

**nccl-test command**
mpirun -n 1 -x FI_PROVIDER=efa -x NCCL_SOCKET_IFNAME=eth0 -x FI_EFA_USE_DEVICE_RDMA=0 -x NCCL_SOCKET_FAMILY=AF_INET -host 192.168.173.233:1 /opt/amazon/nccl-tests/build/all_reduce_perf -b 8 -e 16M -f 2 -g 1 -z 1 -n 5

**nccl-test output**

Warning: Permanently added '[192.168.173.233]:2022' (RSA) to the list of known hosts.
 nThread 1 nGpus 1 minBytes 8 maxBytes 16777216 step: 2(factor) warmup iters: 5 iters: 5 agg iters: 1 validation: 1 graph: 0
 Blocking Enabled: wait for completion and barrier after each collective 

 Using devices
  Rank  0 Group  0 Pid    127 on nccl-846b9d30a6bb6b529fb3c170f4809fea-1725464730-worker-0 device  0 [0x00] NVIDIA A10G

                                                              out-of-place                       in-place          
       size         count      type   redop    root     time   algbw   busbw #wrong     time   algbw   busbw #wrong
        (B)    (elements)                               (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
           8             2     float     sum      -1     9.27    0.00    0.00      0     0.67    0.01    0.00      0
          16             4     float     sum      -1     9.43    0.00    0.00      0     0.67    0.02    0.00      0
          32             8     float     sum      -1     9.79    0.00    0.00      0     0.68    0.05    0.00      0
          64            16     float     sum      -1     9.58    0.01    0.00      0     0.68    0.09    0.00      0
         128            32     float     sum      -1     9.83    0.01    0.00      0     0.70    0.18    0.00      0
         256            64     float     sum      -1     9.52    0.03    0.00      0     0.68    0.38    0.00      0
         512           128     float     sum      -1     9.71    0.05    0.00      0     0.69    0.74    0.00      0
        1024           256     float     sum      -1     9.44    0.11    0.00      0     0.68    1.50    0.00      0
        2048           512     float     sum      -1    10.21    0.20    0.00      0     0.67    3.04    0.00      0
        4096          1024     float     sum      -1     9.70    0.42    0.00      0     0.68    6.06    0.00      0
        8192          2048     float     sum      -1    10.09    0.81    0.00      0     0.70   11.70    0.00      0
       16384          4096     float     sum      -1     9.63    1.70    0.00      0     0.69   23.61    0.00      0
       32768          8192     float     sum      -1     9.58    3.42    0.00      0     0.69   47.22    0.00      0
       65536         16384     float     sum      -1    10.04    6.53    0.00      0     0.69   94.98    0.00      0
      131072         32768     float     sum      -1     9.78   13.40    0.00      0     0.68  192.75    0.00      0
      262144         65536     float     sum      -1    10.09   25.99    0.00      0     0.68  383.25    0.00      0
      524288        131072     float     sum      -1    10.88   48.19    0.00      0     0.71  742.62    0.00      0
     1048576        262144     float     sum      -1    12.99   80.71    0.00      0     0.70  1506.57    0.00      0
     2097152        524288     float     sum      -1    17.38  120.66    0.00      0     0.76  2752.17    0.00      0
     4194304       1048576     float     sum      -1    26.80  156.50    0.00      0     0.68  6150.01    0.00      0
     8388608       2097152     float     sum      -1    46.33  181.05    0.00      0     0.68  12300.01    0.00      0
    16777216       4194304     float     sum      -1    80.69  207.92    0.00      0     0.68  24745.16    0.00      0
 Out of bounds values : 0 OK
 Avg bus bandwidth    : 0 

Could anyone help me to figure out Avg bus bandwidth = 0? Thanks in advance!

**Comment by AddyLaddy** [comment]
You appear to be running on a single GPU. NCCL is a multi-GPU communications library so there's not much to do on a single GPU.

Due to the way BusBW is calculated you end up with 0.

https://github.com/NVIDIA/nccl-tests/blob/master/doc/PERFORMANCE.md

**Comment by rajeshvenkata** [comment]
This makes sense. Thanks for clarifying!
