### ISSUE TITLE
question about pingpong example

### ISSUE THREAD

**Issue by jinz2014** [NVIDIA/nccl-tests#253]
Hello,
Is there a pingpong example in your tests ? Thanks.

      if(rank == 0){
        MPI_Send(d_A, N, MPI_DOUBLE, 1, tag1, MPI_COMM_WORLD);
        MPI_Recv(d_A, N, MPI_DOUBLE, 1, tag2, MPI_COMM_WORLD, &stat);
      }
      else if(rank == 1){
        MPI_Recv(d_A, N, MPI_DOUBLE, 0, tag1, MPI_COMM_WORLD, &stat);
        MPI_Send(d_A, N, MPI_DOUBLE, 0, tag2, MPI_COMM_WORLD);
      }

**Comment by sjeaugey** [comment]
No we only have the `sendrecv` test which is like a ring, performing receive from previous and send to next.

**Comment by jinz2014** [comment]
Will you add a ping-pong test ?  Could you please comment on in-place send/receive  ?

      if(rank == 0){
        NCCLCHECK(ncclGroupStart());
        NCCLCHECK(ncclSend(d_A, N, ncclFloat64, 1, comm, stream));
        NCCLCHECK(ncclRecv(d_A, N, ncclFloat64, 1, comm, stream));
        NCCLCHECK(ncclGroupEnd());
      }
      else if(rank == 1){
        NCCLCHECK(ncclGroupStart());
        NCCLCHECK(ncclRecv(d_A, N, ncclFloat64, 0, comm, stream));
        NCCLCHECK(ncclSend(d_A, N, ncclFloat64, 0, comm, stream));
        NCCLCHECK(ncclGroupEnd());
      }

**Comment by sjeaugey** [comment]
> Will you add a ping-pong test ?

It's not planned.

> Could you please comment on in-place send/receive ?

It's there because all tests run in-place and out-of-place but it's not actually a valid usage as we're not supposed to use the same buffer twice within a group (unless we only read from it). That's why data checks are disabled for in-place sendrecv/alltoall/etc.

**Comment by jinz2014** [comment]
Thanks.

**Comment by jinz2014** [comment]
There is an NCCL version of pingpong:
https://github.com/zjin-lcf/HeCBench/blob/master/src/pingpong-cuda/main-nccl.cu
 
However, the performance of the MPI version is slightly higher than that of the NCCL version.  
https://github.com/zjin-lcf/HeCBench/blob/master/src/pingpong-cuda/main-mpi.cu


/opt/nvidia/hpc_sdk/Linux_x86_64/24.5/comm_libs/mpi/bin/mpirun --mca coll ^hcoll -n 2 ./main-mpi
MPI : Transfer size (B):     524288, Transfer Time (s):     0.000029433, Bandwidth (GB/s):    17.813046053
MPI : Transfer size (B):    1048576, Transfer Time (s):     0.000047102, Bandwidth (GB/s):    22.261639913
MPI : Transfer size (B):    2097152, Transfer Time (s):     0.000085584, Bandwidth (GB/s):    24.504156875
MPI : Transfer size (B):    4194304, Transfer Time (s):     0.000159009, Bandwidth (GB/s):    26.377779017
MPI : Transfer size (B):    8388608, Transfer Time (s):     0.000310447, Bandwidth (GB/s):    27.021093640
MPI : Transfer size (B):   16777216, Transfer Time (s):     0.000628202, Bandwidth (GB/s):    26.706707694
MPI : Transfer size (B):   33554432, Transfer Time (s):     0.001238810, Bandwidth (GB/s):    27.086019867
MPI : Transfer size (B):   67108864, Transfer Time (s):     0.002481997, Bandwidth (GB/s):    27.038255759
MPI : Transfer size (B):  134217728, Transfer Time (s):     0.005027162, Bandwidth (GB/s):    26.698511224
MPI : Transfer size (B):  268435456, Transfer Time (s):     0.010001994, Bandwidth (GB/s):    26.838192910
MPI : Transfer size (B):  536870912, Transfer Time (s):     0.019960704, Bandwidth (GB/s):    26.896392035
MPI : Transfer size (B): 1073741824, Transfer Time (s):     0.040278373, Bandwidth (GB/s):    26.658023987

/opt/nvidia/hpc_sdk/Linux_x86_64/24.5/comm_libs/mpi/bin/mpirun --mca coll ^hcoll -n 2 ./main-nccl
NCCL: Transfer size (B):     524288, Transfer Time (s):     0.000037694, Bandwidth (GB/s):    13.909009175
NCCL: Transfer size (B):    1048576, Transfer Time (s):     0.000060809, Bandwidth (GB/s):    17.243783109
NCCL: Transfer size (B):    2097152, Transfer Time (s):     0.000106089, Bandwidth (GB/s):    19.767782622
NCCL: Transfer size (B):    4194304, Transfer Time (s):     0.000197993, Bandwidth (GB/s):    21.184087489
NCCL: Transfer size (B):    8388608, Transfer Time (s):     0.000378493, Bandwidth (GB/s):    22.163149433
NCCL: Transfer size (B):   16777216, Transfer Time (s):     0.000738849, Bandwidth (GB/s):    22.707234310
NCCL: Transfer size (B):   33554432, Transfer Time (s):     0.001465859, Bandwidth (GB/s):    22.890631643
NCCL: Transfer size (B):   67108864, Transfer Time (s):     0.002908317, Bandwidth (GB/s):    23.074814112
NCCL: Transfer size (B):  134217728, Transfer Time (s):     0.005799309, Bandwidth (GB/s):    23.143745403
NCCL: Transfer size (B):  268435456, Transfer Time (s):     0.011582994, Bandwidth (GB/s):    23.174963701
NCCL: Transfer size (B):  536870912, Transfer Time (s):     0.023147358, Bandwidth (GB/s):    23.193615499
NCCL: Transfer size (B): 1073741824, Transfer Time (s):     0.046243389, Bandwidth (GB/s):    23.219358365
