### ISSUE TITLE
nccl-tests hangs when using HPCX

### ISSUE THREAD

**Issue by ycm0k** [NVIDIA/nccl-tests#255]
On my cluster of H100 systems, I am facing issues with some nodes where nccl-tests hangs ONLY when using HPCX.
The same command works for most nodes but not for some specific nodes. All nodes have been installed and configured exactly the same.

nvidia-smi
![Image](https://github.com/user-attachments/assets/61c06134-6acc-44f7-b5a2-58737c68ed90)

nccl used is cloned and built from https://github.com/NVIDIA/nccl this week

HPCX version v2.20 and loaded with reference to [documentation](https://docs.nvidia.com/networking/display/hpcxv2200/installing+and+loading+hpc-x)
```
cd hpcx
export HPCX_HOME=$PWD
source $HPCX_HOME/hpcx-init.sh
hpcx_load
```

Command used:
```
mpirun -np 16 -N 8 \
-H hgx-020:8,hgx-012:8 \
-x NCCL_DEBUG=info \
-x LD_LIBRARY_PATH \
-x NCCL_IB_QPS_PER_CONNECTION=2 \
-x NCCL_IB_SPLIT_DATA_ON_QPS=0 \
./all_reduce_perf -b 128 -e 16G -f 2 -g 1
```

I am able to run nccl-tests without using HPCX, or if I specify `-x LD_LIBRARY_PATH=/nccl/build/lib \` while using HPCX, which is able to run nccl-tests, but outputs the following warning:
![Image](https://github.com/user-attachments/assets/1f5e9f27-f0ec-4653-adb1-826716a04063)

**Comment by ycm0k** [comment]
[hgx-012.log](https://github.com/user-attachments/files/17270131/hgx-012.log)
[hgx-014.log](https://github.com/user-attachments/files/17270132/hgx-014.log)
adding logs for 2 nodes with same issues

**Comment by AddyLaddy** [comment]
It doesn't look like NCCL is even starting from the failure traces, so I suspect this is due to mpirun and UCX issues.
Maybe try `-x UCX_TLS=tcp`
I'd also try and run a simple multi-node MPI test to confirm that mpirun is functional before trying NCCL.

**Comment by ycm0k** [comment]
> It doesn't look like NCCL is even starting from the failure traces, so I suspect this is due to mpirun and UCX issues. Maybe try `-x UCX_TLS=tcp` I'd also try and run a simple multi-node MPI test to confirm that mpirun is functional before trying NCCL.

Thanks for the input! You were right, UCX was causing problems. Managed to get everything working by reinstalling the whole set-up; The problem had nothing to do with nccl-test but rather a faulty installation of UCX, so I'm closing this issue.
