### ISSUE TITLE
multiple processes 

### ISSUE THREAD

**Issue by Sampson1107** [NVIDIA/nccl-tests#3]
The test rely on MPI to work on multiple processes. Does the multiple processes must reply on MPI? Can the NCCL2 work with rpc  while using two or more machines?

**Comment by sjeaugey** [comment]
If you want to run NCCL on multiple nodes, you will need a system to launch and manage processes, a mechanism to perform some CPU-to-CPU communication, and a way to compute the NCCL rank number. MPI is providing all of that, but it is not required : you may replace it with any other parallel environment.

**Comment by Sampson1107** [comment]
@sjeaugey 
Ok, thanks a lot!
