### ISSUE TITLE
mpi.h: No such file or directory

### ISSUE THREAD

**Issue by scottzockoll** [NVIDIA/nccl-tests#32]
When I run the following command:
```
make MPI=1 MPI_HOME=/usr/include/mpi NCCL_HOME=/usr/local
```
I get the following error:
```
common.h:14:17: fatal error: mpi.h: No such file or directory
# include "mpi.h"
```
However I am able to verify that mpi.h is in that directory

**Comment by sjeaugey** [comment]
The `$MPI_HOME` variable in the `Makefile`assumes includes are in `$MPI_HOME/include` and libraries are in `$MPI_HOME/lib`. In most cases, `/usr/include/mpi` is just a link, and the real MPI installation is in `/usr/lib/openmpi` (both includes and library). Setting `MPI_HOME=/usr/lib/openmpi` would solve the problem.

Another simple solution is to add `/usr/include/mpi` to the path of `g++` includes :
```
export CPLUS_INCLUDE_PATH=/usr/include/mpi:$CPLUS_INCLUDE_PATH
```

And if the libraries are not found (`cannot find -lmpi`), we can also tell `g++` where to find libraries :
```
export LIBRARY_PATH=/usr/lib/openmpi/lib:$LIBRARY_PATH
```
(but usually there is a link in `/usr/lib/libmpi.so` so it shouldn't be needed)

**Comment by scottzockoll** [comment]
Hello,
I am using a Jetson Nano cluster and /usr/lib/openmpi does not exist. It seems the mpi is installed because I get the following output when I run `mpirun --version`:
```
mpirun (Open MPI) 2.2.1

Report bugs to http://www.open-mpi.org/community/help/
```

**Comment by sjeaugey** [comment]
On ARM platforms, the path to Open MPI might be something like `/usr/lib/aarch64-linux-gnu/openmpi`.

`mpicc -show` would show where MPI includes and library are located, then you can use `MPI_HOME` or `CPLUS_INCLUDE_PATH`/`LIBRARY_PATH` to make sure `g++` finds them well.

Please note however that NCCL is not targeted at Jetson Nano so I would not expect it to work.

**Comment by scottzockoll** [comment]
I was able to find it under `/usr/lib/aarch64-linux-gnu/openmpi` However when running the command `mpirun -np 16 ./build/all_reduce_perf -b 32M -e 128M -f 2 -t 1 -g 1 -c 0` the following error ouputs:

```
./build/all_reduce_perf: error while loading shared libraries: libnccl.so.2: cannot open shared object file: No such file or directory
```
But from my understanding this should be found under the NCCL_HOME variable?

**Comment by sjeaugey** [comment]
If you did not install NCCL on the system (just compiled it in your home directory), you need to set `LD_LIBRARY_PATH` :
```
export LD_LIBRARY_PATH=$NCCL_HOME/build/lib:$LD_LIBRARY_PATH
```

**Comment by AddyLaddy** [comment]
Closing old issues. Please open another one if you are still seeing issues.
