### ISSUE TITLE
/usr/bin/ld:cannot find -lmpi

### ISSUE THREAD

**Issue by Dongguage** [NVIDIA/nccl-tests#34]
Hi, I encountered this error while compiling:

/usr/bin/ld:cannot find -lmpi

I have installed openmpi 4.0.2 to /openmpi4.0, and specified the MPI_HOME to be here.

Thank you!

**Comment by sjeaugey** [comment]
Can you check is `$MPI_HOME/lib/libmpi.so` exists ?

**Comment by AddyLaddy** [comment]
Closing old issues. Please open another one if you are still seeing issues.
