### ISSUE TITLE
MPI_HOME alone is not able to build since mpi.h does not reside in /usr/include/mpi.h

### ISSUE THREAD

**Issue by 372046933** [NVIDIA/nccl-tests#39]
On CentOS 7, `openmpi-devel` have `libmpi.so` in `/usr/lib64/openmpi/lib/libmpi.so` and `mpi.h` resides in `/usr/include/openmpi-x86_64/mpi.h`

**Comment by AddyLaddy** [comment]
Is this still an issue, were you able to find a workaround ?

**Comment by 372046933** [comment]
Sorry, I didn't run the test afterwards

**Comment by AddyLaddy** [comment]
Ok I'll close the issue. Please feel to open a new one if you hit more issues.
