### ISSUE TITLE
Is NCCL suitable for calculating "sum = a1 + a2 + .. +an;"?

### ISSUE THREAD

**Issue by NanXiao** [NVIDIA/nccl-tests#4]
Hi @sjeaugey 

Greetings from me! I am a newbie of `GPU` programming and not sure whether this is  the correct place to submit this issue here, if I am wrong, please forgive me, thanks!

After referring [Fast Multi-GPU collectives with NCCL](https://devblogs.nvidia.com/parallelforall/fast-multi-gpu-collectives-nccl/) and using [nccl-tests](https://github.com/NVIDIA/nccl-tests), I find `NCCL` seems most powerful in following case:  

    A[0] = A[0] + B[0] +C[0] + D[0];
    ......
    A[n] = A[n] + B[n] +C[n] + D[n];

where the array count is less than `GPU` count, and `n` is a large number. But not applicable for following case:    

    sum = a1 + a2 + .. +an;

Is my understanding correct? If I want to utilize multiple `GPU` s to accelerate calculating `sum = a1 + a2 + .. +an;`, is there any canonical method?

Thanks very much in advance!

Best Regards
Nan Xiao

**Comment by sjeaugey** [comment]
To perform intra-GPU reductions, I suggest you look at the CUB library. There should be functions doing what you need.

**Comment by AddyLaddy** [comment]
No further feedback so I'll close this issue. Please open another one if you are still seeing issues.
