### ISSUE TITLE
"Benchmark" tests

### ISSUE THREAD

**Issue by rxk900** [NVIDIA/nccl-tests#40]
Apologies if this is not the correct place to post this.
Sat in on the excellent Connect with the Experts NCCL session this morning. I may not have heard correctly but I was under the impression there was a page somewhere with expected performance numbers for comparison. What I thought I heard was to run the Perf tests from this github link and compare with the numbers at ?????  "to check your hardware is working at the speed it should be". I was expecting to find some table with expected numbers for typical platforms but couldn't immediately find anything. Did I misunderstand something?

**Comment by sjeaugey** [comment]
Hi,
NCCL Performance tests are at https://github.com/nvidia/nccl-tests.

The "Bus BW" column should reach the peak bandwidth of your platform (depending on intra-node and inter-node bandwidth), for large enough sizes.

Feel free to report numbers you get if you're unsure.

**Comment by rxk900** [comment]
That makes sense - it all boils down to bandwidth.
I've "delegated" this to one of our system guys who said he'll get on to this next week.
Thx and Thx for an awesome session.
