### ISSUE TITLE
Internal error

### ISSUE THREAD

**Issue by hpadhuka** [NVIDIA/nccl-tests#41]
I'm unable to get the nccl-test to run successfully. It fails with an internal error.
```
Singularity> ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 4
# nThread 1 nGpus 4 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 1
#
# Using devices
#   Rank  0 Pid 108039 on ip-0AB85F07 device  0 [0x00] Tesla V100-PCIE-16GB
#   Rank  1 Pid 108039 on ip-0AB85F07 device  1 [0x00] Tesla V100-PCIE-16GB
#   Rank  2 Pid 108039 on ip-0AB85F07 device  2 [0x00] Tesla V100-PCIE-16GB
#   Rank  3 Pid 108039 on ip-0AB85F07 device  3 [0x00] Tesla V100-PCIE-16GB
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs0
ip-0AB85F07: Test NCCL failure common.cu:775 'internal error'
```

**Comment by sjeaugey** [comment]
The warning means that your container is missing some packages for IB verbs, probably libmlx5.

I'm still not sure why we see an "internal error" here. Can you set `NCCL_DEBUG=INFO` and run again ?

**Comment by hpadhuka** [comment]
Thanks a lot for the assist. The log after setting debug.

Singularity> ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 4
# nThread 1 nGpus 4 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 1
#
# Using devices
#   Rank  0 Pid  22097 on ip-0AB85F07 device  0 [0x00] Tesla V100-PCIE-16GB
#   Rank  1 Pid  22097 on ip-0AB85F07 device  1 [0x00] Tesla V100-PCIE-16GB
#   Rank  2 Pid  22097 on ip-0AB85F07 device  2 [0x00] Tesla V100-PCIE-16GB
#   Rank  3 Pid  22097 on ip-0AB85F07 device  3 [0x00] Tesla V100-PCIE-16GB
ip-0AB85F07:22097:22097 [0] NCCL INFO Bootstrap : Using [0]eth0:10.184.95.7<0> [1]eth1:fe80::5219:4543:1f44:14ac%eth1<0>
ip-0AB85F07:22097:22097 [0] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so), using internal implementation
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs0
ip-0AB85F07:22097:22097 [0] NCCL INFO NET/IB : No device found.
ip-0AB85F07:22097:22097 [0] NCCL INFO NET/Socket : Using [0]eth0:10.184.95.7<0> [1]eth1:fe80::5219:4543:1f44:14ac%eth1<0>
NCCL version 2.5.6+cuda10.2
ip-0AB85F07:22097:22117 [3] NCCL INFO Setting affinity for GPU 3 to 01
ip-0AB85F07:22097:22116 [2] NCCL INFO Setting affinity for GPU 2 to 01
ip-0AB85F07:22097:22115 [1] NCCL INFO Setting affinity for GPU 1 to 01
ip-0AB85F07:22097:22114 [0] NCCL INFO Setting affinity for GPU 0 to 01

ip-0AB85F07:22097:22117 [3] graph/paths.cc:155 NCCL WARN Error : could not find CPU close to GPU 0
ip-0AB85F07:22097:22117 [3] NCCL INFO graph/paths.cc:220 -> 3
ip-0AB85F07:22097:22117 [3] NCCL INFO init.cc:471 -> 3
ip-0AB85F07:22097:22117 [3] NCCL INFO init.cc:732 -> 3
ip-0AB85F07:22097:22117 [3] NCCL INFO group.cc:63 -> 3 [Async thread]

ip-0AB85F07:22097:22114 [0] graph/paths.cc:155 NCCL WARN Error : could not find CPU close to GPU 0
ip-0AB85F07:22097:22114 [0] NCCL INFO graph/paths.cc:220 -> 3
ip-0AB85F07:22097:22114 [0] NCCL INFO init.cc:471 -> 3
ip-0AB85F07:22097:22114 [0] NCCL INFO init.cc:732 -> 3
ip-0AB85F07:22097:22114 [0] NCCL INFO group.cc:63 -> 3 [Async thread]

ip-0AB85F07:22097:22115 [1] graph/paths.cc:155 NCCL WARN Error : could not find CPU close to GPU 0
ip-0AB85F07:22097:22115 [1] NCCL INFO graph/paths.cc:220 -> 3
ip-0AB85F07:22097:22115 [1] NCCL INFO init.cc:471 -> 3
ip-0AB85F07:22097:22115 [1] NCCL INFO init.cc:732 -> 3
ip-0AB85F07:22097:22115 [1] NCCL INFO group.cc:63 -> 3 [Async thread]

ip-0AB85F07:22097:22116 [2] graph/paths.cc:155 NCCL WARN Error : could not find CPU close to GPU 0
ip-0AB85F07:22097:22116 [2] NCCL INFO graph/paths.cc:220 -> 3
ip-0AB85F07:22097:22116 [2] NCCL INFO init.cc:471 -> 3
ip-0AB85F07:22097:22116 [2] NCCL INFO init.cc:732 -> 3
ip-0AB85F07:22097:22116 [2] NCCL INFO group.cc:63 -> 3 [Async thread]
ip-0AB85F07:22097:22097 [3] NCCL INFO init.cc:801 -> 3
ip-0AB85F07: Test NCCL failure common.cu:775 'internal error'

**Comment by sjeaugey** [comment]
Thanks for the log. It is weird that you end up there, but it's probably due to some missing pieces in your container.

Setting `NCCL_DEBUG_SUBSYS=GRAPH` (on top of `NCCL_DEBUG=INFO`) and dumping the topology with `NCCL_TOPO_DUMP_FILE=system.xml` would tell us more. Also, running with NCCL 2.6 would ensure this problem is still relevant with the latest version.

**Comment by hpadhuka** [comment]
I believe the container image is of 
https://docs.nvidia.com/deeplearning/frameworks/tensorflow-release-notes/rel_19.12.html#rel_19.12

Sorry I don't see a system.xml after setting NCCL_TOPO_DUMP_FILE. Is there anything else needed to dump ?
The log below.

Singularity> ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 4
# nThread 1 nGpus 4 minBytes 8 maxBytes 134217728 step: 2(factor) warmup iters: 5 iters: 20 validation: 1
#
# Using devices
#   Rank  0 Pid  24352 on ip-0AB85F07 device  0 [0x00] Tesla V100-PCIE-16GB
#   Rank  1 Pid  24352 on ip-0AB85F07 device  1 [0x00] Tesla V100-PCIE-16GB
#   Rank  2 Pid  24352 on ip-0AB85F07 device  2 [0x00] Tesla V100-PCIE-16GB
#   Rank  3 Pid  24352 on ip-0AB85F07 device  3 [0x00] Tesla V100-PCIE-16GB
libibverbs: Warning: no userspace device-specific driver found for /sys/class/infiniband_verbs/uverbs0
NCCL version 2.5.6+cuda10.2
ip-0AB85F07:24352:24369 [0] NCCL INFO /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/000d3a25-3f7a-000d-3a25-3f7a000d3a25 -> 0/0/0/0
ip-0AB85F07:24352:24369 [0] NCCL INFO /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/00155d33-ff1c-0015-5d33-ff1c00155d33 -> 1/1/0/1

ip-0AB85F07:24352:24369 [0] graph/paths.cc:155 NCCL WARN Error : could not find CPU close to GPU 0
ip-0AB85F07:24352:24369 [0] NCCL INFO graph/paths.cc:220 -> 3
ip-0AB85F07:24352:24369 [0] NCCL INFO init.cc:471 -> 3
ip-0AB85F07:24352:24369 [0] NCCL INFO init.cc:732 -> 3
ip-0AB85F07:24352:24372 [3] NCCL INFO /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/000d3a25-3f7a-000d-3a25-3f7a000d3a25 -> 0/0/0/0
ip-0AB85F07:24352:24372 [3] NCCL INFO /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/00155d33-ff1c-0015-5d33-ff1c00155d33 -> 1/1/0/1

ip-0AB85F07:24352:24372 [3] graph/paths.cc:155 NCCL WARN Error : could not find CPU close to GPU 0
ip-0AB85F07:24352:24372 [3] NCCL INFO graph/paths.cc:220 -> 3
ip-0AB85F07:24352:24372 [3] NCCL INFO init.cc:471 -> 3
ip-0AB85F07:24352:24372 [3] NCCL INFO init.cc:732 -> 3
ip-0AB85F07:24352:24371 [2] NCCL INFO /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/000d3a25-3f7a-000d-3a25-3f7a000d3a25 -> 0/0/0/0
ip-0AB85F07:24352:24371 [2] NCCL INFO /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/00155d33-ff1c-0015-5d33-ff1c00155d33 -> 1/1/0/1

ip-0AB85F07:24352:24371 [2] graph/paths.cc:155 NCCL WARN Error : could not find CPU close to GPU 0
ip-0AB85F07:24352:24371 [2] NCCL INFO graph/paths.cc:220 -> 3
ip-0AB85F07:24352:24371 [2] NCCL INFO init.cc:471 -> 3
ip-0AB85F07:24352:24371 [2] NCCL INFO init.cc:732 -> 3
ip-0AB85F07:24352:24370 [1] NCCL INFO /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/000d3a25-3f7a-000d-3a25-3f7a000d3a25 -> 0/0/0/0
ip-0AB85F07:24352:24370 [1] NCCL INFO /sys/devices/LNXSYSTM:00/device:00/PNP0A03:00/device:08/VMBUS:01/00155d33-ff1c-0015-5d33-ff1c00155d33 -> 1/1/0/1

ip-0AB85F07:24352:24370 [1] graph/paths.cc:155 NCCL WARN Error : could not find CPU close to GPU 0
ip-0AB85F07:24352:24370 [1] NCCL INFO graph/paths.cc:220 -> 3
ip-0AB85F07:24352:24370 [1] NCCL INFO init.cc:471 -> 3
ip-0AB85F07:24352:24370 [1] NCCL INFO init.cc:732 -> 3
ip-0AB85F07:24352:24352 [3] NCCL INFO init.cc:801 -> 3
ip-0AB85F07: Test NCCL failure common.cu:775 'internal error'

**Comment by sjeaugey** [comment]
Ok, unfortunately the crash seems to happen before the XML dump or the topology print is performed, so I can't see anything.

Upgrading to the latest NCCL should be something like this (on Ubuntu) :
```
git clone https://github.com/nvidia/nccl
apt install build-essential devscripts debhelper fakeroot
make pkg.debian.build
dpkg -i build/pkg/deb/*.deb
```
Recompiling from source will also allow us to easily add more debug if needed.

**Comment by AddyLaddy** [comment]
No further feedback so I'll close this issue. Please open another one if you are still seeing issues.
