### ISSUE TITLE
Feature request: write results to file

### ISSUE THREAD

**Issue by christopherhesse** [NVIDIA/nccl-tests#42]
I'm trying to run nccl-tests and then parse the output, but it's kind of a pain if debug output is enabled because it mixes with the actual output.  Would it be possible to have an option to write to a CSV file instead of just stdout?

**Comment by AddyLaddy** [comment]
NCCL supports logging of the INFO output to a file using `NCCL_DEBUG_FILE`
I also find just using grep for say `float` allows me to extract the performance data I need from the nccl-tests output.

**Comment by AddyLaddy** [comment]
Hopefully the suggestions above help. Closing this issue.

**Comment by christopherhesse** [comment]
Thanks!  I think `NCCL_DEBUG_FILE` will work, simply grepping for float didn't work because in the middle of the output table there would be a debug line that I would have to remove with a regular expression.
