### ISSUE TITLE
ncclSend and ncclRecv undefined

### ISSUE THREAD

**Issue by joehandzik** [NVIDIA/nccl-tests#47]
When compiling in a container without CUDA 11...

Step 11/28 : RUN make MPI=1 MPI_HOME=/usr/local/mpi
 ---> Running in bc5f12a8f538
make -C src build
make[1]: Entering directory '/nccl-tests/src'
Compiling  all_reduce.cu                       > ../build/all_reduce.o
Compiling  common.cu                           > ../build/common.o
Linking  ../build/all_reduce.o               > ../build/all_reduce_perf
Compiling  all_gather.cu                       > ../build/all_gather.o
Linking  ../build/all_gather.o               > ../build/all_gather_perf
Compiling  broadcast.cu                        > ../build/broadcast.o
Linking  ../build/broadcast.o                > ../build/broadcast_perf
Compiling  reduce_scatter.cu                   > ../build/reduce_scatter.o
Linking  ../build/reduce_scatter.o           > ../build/reduce_scatter_perf
Compiling  reduce.cu                           > ../build/reduce.o
Linking  ../build/reduce.o                   > ../build/reduce_perf
Compiling  alltoall.cu                         > ../build/alltoall.o
alltoall.cu(69): error: identifier "ncclSend" is undefined

alltoall.cu(70): error: identifier "ncclRecv" is undefined

2 errors detected in the compilation of "/tmp/tmpxft_00000461_00000000-10_alltoall.compute_70.cpp1.ii".
Makefile:71: recipe for target '../build/alltoall.o' failed
make[1]: *** [../build/alltoall.o] Error 1
make[1]: Leaving directory '/nccl-tests/src'
make: *** [src.build] Error 2
Makefile:17: recipe for target 'src.build' failed
The command '/bin/sh -c make MPI=1 MPI_HOME=/usr/local/mpi' returned a non-zero code: 2

Is it expected that we won't be able to compile this code without CUDA 11?

**Comment by sjeaugey** [comment]
That's not tied to CUDA, but with the NCCL version. You need NCCL 2.7 to have Send/Recv.
I'll see if we can detect the version of NCCL and do the right thing.

**Comment by joehandzik** [comment]
Ah, my mistake. Makes sense. Thanks for taking a look.

**Comment by sjeaugey** [comment]
Should be fixed now -- please reopen if not.

**Comment by Honei** [comment]
make -C src build
make[1]: Entering directory '/home/users/xiongxinlei/tool/nccl-tests/src'
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Compiling  all_reduce.cu                       > ../build/all_reduce.o
Compiling  common.cu                           > ../build/common.o
Linking  ../build/all_reduce.o               > ../build/all_reduce_perf
Compiling  all_gather.cu                       > ../build/all_gather.o
Linking  ../build/all_gather.o               > ../build/all_gather_perf
Compiling  broadcast.cu                        > ../build/broadcast.o
Linking  ../build/broadcast.o                > ../build/broadcast_perf
Compiling  reduce_scatter.cu                   > ../build/reduce_scatter.o
Linking  ../build/reduce_scatter.o           > ../build/reduce_scatter_perf
Compiling  reduce.cu                           > ../build/reduce.o
Linking  ../build/reduce.o                   > ../build/reduce_perf
Compiling  alltoall.cu                         > ../build/alltoall.o
Linking  ../build/alltoall.o                 > ../build/alltoall_perf
../build/alltoall.o: In function `AlltoAllRunColl(void*, void*, unsigned long, ncclDataType_t, ncclRedOp_t, int, ncclComm*, CUstream_st*)':
/home/users/xiongxinlei/tool/nccl-tests/src/alltoall.cu:74: undefined reference to `ncclRecv'
/home/users/xiongxinlei/tool/nccl-tests/src/alltoall.cu:73: undefined reference to `ncclSend'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:89: ../build/alltoall_perf] Error 1
make[1]: Leaving directory '/home/users/xiongxinlei/tool/nccl-tests/src'
make: *** [Makefile:17: src.build] Error 2


nccl version: 2.11.4

**Comment by sjeaugey** [comment]
It would seem the NCCL tests are trying to link against an older version of NCCL which is also installed on the system.

Where is NCCL 2.11.4 located? You may want to pass `NCCL_HOME=/path/to/nccl-2.11.4` to your make command line.
