### ISSUE TITLE
show me the nccl.h is not found. who can help me ??  ^_^

### ISSUE THREAD

**Issue by harrycrq** [NVIDIA/nccl-tests#51]
~~# make
make -C src build
make[1]: Entering directory `/root/nccl-tests/src'
Compiling  all_reduce.cu                       > ../build/all_reduce.o
In file included from all_reduce.cu:8:0:
common.h:9:18: fatal error: nccl.h: No such file or directory
 #include "nccl.h"
                  ^
compilation terminated.
make[1]: *** [../build/all_reduce.o] Error 1
make[1]: Leaving directory `/root/nccl-tests/src'
make: *** [src.build] Error 2

**Comment by kwen2501** [comment]
You may overcome this issue by setting NCCL_HOME to the path to NCCL on your system. See README.md.

**Comment by AddyLaddy** [comment]
No further feedback so I'll close this issue. Please open another one if you are still seeing issues.
