### ISSUE TITLE
why the Out of Bounds values is 0? 

### ISSUE THREAD

**Issue by Hamidreza-Ramezani** [NVIDIA/nccl-tests#52]
Hello everyone! 

After running nccl tests linked with my nccl [fork](https://github.com/Hamidreza-Ramezani/nccl), I got a result as you can see in this photo: 

![1](https://user-images.githubusercontent.com/43248009/95860374-458fb700-0d60-11eb-9e0e-86f28cd20e20.png)

Although the error column in the attached photo has meaningful numbers rather than 0, the final result which is Out of Bounds Values is 0 and it seems all tests are passed. I would like to know why that happened?

**Comment by sjeaugey** [comment]
Floating point operations incur some natural rounding error. NCCL tests take that into account and only report errors which are out of bounds.

**Comment by Hamidreza-Ramezani** [comment]
@sjeaugey Thank you :)
