### ISSUE TITLE
Run with MPI on 40 processes test failed.

### ISSUE THREAD

**Issue by TimJZ** [NVIDIA/nccl-tests#54]
GPU driver: 440.82
CUDA: 11.0, 
NCCL: 2704
One node with 4 Tesla V100-SXM2 GPUs.

I've tried running the tests with one node and 4 GPUs with no problems. 

However, my test with MPI on 40 processes failed. Here's the command I ran: 

mpirun -np 40 ./build/all_gather_perf -b 8 -e 128M -f 2 -g 4

The error I got was: 

 nThread 1 nGpus 1 minBytes 0 maxBytes 134217728 step: 1048576(bytes) warmup iters: 5 iters: 20 validation: 1 

 Using devices
e860e6c2d0e6: Test CUDA failure common.cu:732 'invalid device ordinal'
e860e6c2d0e6: Test CUDA failure common.cu:732 'invalid device ordinal'
e860e6c2d0e6: Test CUDA failure common.cu:732 'invalid device ordinal'
e860e6c2d0e6: Test CUDA failure common.cu:732 'invalid device ordinal'
e860e6c2d0e6: Test CUDA failure common.cu:732 'invalid device ordinal'
e860e6c2d0e6: Test CUDA failure common.cu:732 'invalid device ordinal'
e860e6c2d0e6: Test CUDA failure common.cu:732 'invalid device ordinal'
e860e6c2d0e6: Test CUDA failure common.cu:732 'invalid device ordinal'
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[20089,1],20]
  Exit code:    2

However, when I tried to run the same command with number of processes <= 4, I got no problems. I'm wondering if this is the expected behavior at all. I was assuming the 4 GPUs with 1 node could support more than 4 processes, especially since the readme only mentioned that "Run with MPI could pontentially support multple nodes with 4 GPUs each". Would really appreciate some help if anyone could help me figure this out. Thanks!

**Comment by kwen2501** [comment]
Hi, the test option of `-g 4` would require 4 GPUs per CPU thread. Thus, in your command

**Comment by TimJZ** [comment]
Thank you very much for the explanation!

**Comment by YunchaoYang** [comment]
Thanks @kwen2501 for the explanation! This help solve my problem.

I think the MPI-40 process example is very confusing. It gave me the impression that the test was done for 10 nodes with a total of 40 GPUs.

**Comment by MasterSkepticista** [comment]
How do I test this to measure NCCL across 2 GPUs, each on a separate server, connected via ethernet?
I tried providing `mpirun -n 2 -hostfile hostfile ./nccl-tests/build/all_reduce_perf -f 2 -g 1`, but it fails with same error as shown:

```bash
No protocol specified
No protocol specified
# nThread 1 nGpus 1 minBytes 33554432 maxBytes 33554432 step: 2(factor) warmup iters: 5 iters: 20 agg iters: 1 validation: 1 graph: 0
#
# Using devices
machine1: Test CUDA failure common.cu:892 'invalid device ordinal'
 .. machine1 pid 21004: Test failure common.cu:842
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[25510,1],1]
  Exit code:    2
--------------------------------------------------------------------------
```

**Comment by AddyLaddy** [comment]
Are you sure you're running the two processes on different nodes?
Try running ```mpirun -n 2 -hostfile hostfile hostname``` to check. Also use the mpirun option ```-N 1``` to force the number of ranks per node.
