### ISSUE TITLE
common.cu:375

### ISSUE THREAD

**Issue by Hamidreza-Ramezani** [NVIDIA/nccl-tests#55]
Hello everyone! I had two questions regarding nccl-tests: 

1- why a shift is made in [common.cu:375](https://github.com/NVIDIA/nccl-tests/blob/master/src/common.cu#L375-L376).

2- Is it enough to check the correctness of nccl by nccl-tests when the number of iters and number of warm-up iters inside nccl-tests are set to 0?

Best,

**Comment by sjeaugey** [comment]
1- that's to avoid cache effects and have performance numbers that make more sense.

2- probably yes.

**Comment by Hamidreza-Ramezani** [comment]
@sjeaugey Thank you.
