### ISSUE TITLE
datacheck in nccl-tests

### ISSUE THREAD

**Issue by hamid-ramezani** [NVIDIA/nccl-tests#56]
Hi everyone! 

I would like to know what exactly [datacheck](https://github.com/NVIDIA/nccl-tests/blob/bd0755c95c16a751dca7d5ef8994e76f3cd7642a/src/common.cu#L33) represents in nccl-tests? In the README it is written that the -c option is for checking the correctness of results. This is a bit unclear to me since the tests are essentially for checking the correctness (so what is the point of datacheck?). And, I am wondering what happens if one sets -c into 0?

**Comment by AddyLaddy** [comment]
The datacheck option is enabled by default. The NCCL tests are used for both data integrity and performance testing. Setting it to 0 will disable the data integrity checks, but that option is rarely used.

**Comment by hamid-ramezani** [comment]
@AddyLaddy Thanks :)

**Comment by hamid-ramezani** [comment]
@AddyLaddy Are warmup iters and iters (-w and -n options) only dealing with performance testing? So, if I am caring only about data integrity, is it safe to set them to 0?

**Comment by sjeaugey** [comment]
Yes -w and -n are only for performance.

**Comment by hamid-ramezani** [comment]
@sjeaugey Thanks :)
