### ISSUE TITLE
GPU affinity sets different CPU masks when using the same NCCL_TOPO_FILE

### ISSUE THREAD

**Issue by rexcsn** [NVIDIA/nccl-tests#57]
Hi,

When running `all_reduce_perf`, NCCL sets different CPU masks when running the test through Slurm scheduler as opposed to running directly with OpenMPI. Both tests runs with the same `NCCL_TOPO_FILE` variable.
```
# Running with slurm:
[0] NCCL INFO NET/OFI Running on P4d platform, Setting NCCL_TOPO_FILE environment variable to /usr/local/cuda-11.0/efa/share/aws-ofi-nccl/xml/p4d-24xl-topo.xml
...
[0] NCCL INFO Setting affinity for GPU 0 to ff

# Running with OpenMPI
[0] NCCL INFO NET/OFI Running on P4d platform, Setting NCCL_TOPO_FILE environment variable to /usr/local/cuda-11.0/efa/share/aws-ofi-nccl/xml/p4d-24xl-topo.xml
...
[0] NCCL INFO Setting affinity for GPU 0 to ffffff
```

Why would this happen? Are we missing any Slurm configuration or NCCL environment variable we need to set?

Thank you!

**Comment by AddyLaddy** [comment]
I'm not sure why OpenMPI and SLURM are setting different affinity masks, but you can ask NCCL to ignore the supplied CPU affinity mask and just use the the GPU one by setting `NCCL_IGNORE_CPU_AFFINITY=1` in the environment.

**Comment by sjeaugey** [comment]
Affinity is launcher dependent.

`mpirun` will bind ranks to cores depending on the `--bind-to` option (and you can add `--report-bindings` to see what it did). 

SLURM has its own binding system, with `srun` having a `--cpu-bind` option. If you're launching with `salloc .. mpirun`, mpirun will use `srun` under the hood to spawn tasks on the nodes, but I don't know what `--cpu-bind` option it will use and how the binding will work in that case.

**Comment by AddyLaddy** [comment]
No recent feedback, closing this issue.
