### ISSUE TITLE
Test NCCL failure common.cu:752 'internal error'

### ISSUE THREAD

**Issue by yaodanduthit** [NVIDIA/nccl-tests#58]
I want to test NCCL in Docker environment mlperf-nvidia:image_classification.
The following results are generated when I run quick test:
![image](https://user-images.githubusercontent.com/37663460/101317108-ccf93280-3898-11eb-92d7-9bc40b13c32f.png)
And the docker container's CUDA environment is:
![image](https://user-images.githubusercontent.com/37663460/101317228-07fb6600-3899-11eb-843b-0b57d0e141c6.png)
how can I fix this. Tanks

**Comment by huxiaotaostasy** [comment]
请问你解决了吗
