### ISSUE TITLE
NCCL failure common.cu:908 'unhandled cuda error'

### ISSUE THREAD

**Issue by galphag** [NVIDIA/nccl-tests#6]
I have installed cuda 8.0.61, cudnn 5.1.10 and nccl 2.1.15 on Ubuntu 14.04. I have successfully verified cuda and cudnn using official examples. 
However, I run into errors using nccl-tests
$ ./build/all_reduce_perf -b 8 -e 128M -f 2 -g 4
NCCL failure common.cu:908 'unhandled cuda error'.

I have tried to install nccl2 locally and using network repo. But both ways failed. 

Anyone can help?

**Comment by sjeaugey** [comment]
Can you please set NCCL_DEBUG=WARN in your environment ? That would give you a better error message.

Also can you paste the full output of the test ?

Thanks !

**Comment by qysnn** [comment]
The error I have is `Test NCCL failure common.cu:777 'unhandled cuda error'`. By using `NCCL_DEBUG=WARN` I notice that my nccl depends on a different CUDA version (11.0) than I have on my system(10.2). Installing the correct nccl version fixs the problem for me. 

`sudo apt install libnccl-dev=2.9.8-1+cuda10.2 libnccl2=2.9.8-1+cuda10.2`
