### ISSUE TITLE
when run test in default,  How can I determine what nccl-algorithm is used

### ISSUE THREAD

**Issue by huyutuo** [NVIDIA/nccl-tests#65]
when I run test without using "-x NCCL_ALGO=xx", how can i determine what nccl-algorithm is used.
when i run test in my environment， I can determine ring algorithm is used by speed, because I  find ring is fast than tree in my environment, and when i run test without using "-x NCCL_ALGO=xx", the speed is similar to ring'speed.

I have run test with  “-x NCCL_DEBUG=INFO”, but i can't find any message that i can  determine what algorithm is used 

Is there a definite way to determine what algorithm is used at runtime？

thanks

**Comment by sjeaugey** [comment]
The ALGO/PROTO combination used is dependent on the size of the operation.

You can set `NCCL_DEBUG_SUBSYS=TUNING NCCL_DEBUG=INFO` to print the tuning table, but the numbers are just the base for the computation which will eventually decide which ALGO/PROTO to use at a given size.

Now if you're curious, you can always replace `TRACE` by `INFO` [here](https://github.com/NVIDIA/nccl/blob/master/src/enqueue.cc#L302) and set `NCCL_DEBUG_SUBSYS=COLL`.

**Comment by AddyLaddy** [comment]
No further feedback so I'll close this issue. Please open another one if you are still seeing issues.
