### ISSUE TITLE
Out of bounds values : 248 FAILED

### ISSUE THREAD

**Issue by wm10240** [NVIDIA/nccl-tests#7]
hi,   when I use command "mpirun -v --allow-run-as-root -x NCCL_SOCKET_IFNAME=ib0  -x NCCL_IB_CUDA_SUPPORT=1 -mca btl_tcp_if_include ib0 -np 2 -host 192.168.1.14,192.168.1.13 
-pernode ./build/all_reduce_perf -b 9 -e 32M -g 8 -c 1 -z 0" , the result show "Out of bounds values : 248 FAILED",  I have no idea about this error, So It‘s Very grateful that you have any message to me about this error。

The result：

--------------------------------------------------------------------------
WARNING: There are more than one active ports on host 'seedsmed-f02hpc02', but the
default subnet GID prefix was detected on more than one of these
ports.  If these ports are connected to different physical IB
networks, this configuration will fail in Open MPI.  This version of
Open MPI requires that every physically separate IB subnet that is
used between connected MPI processes must have different subnet ID
values.

Please see this FAQ entry for more details:

  http://www.open-mpi.org/faq/?category=openfabrics#ofa-default-subnet-gid

NOTE: You can turn off this warning by setting the MCA parameter
      btl_openib_warn_default_gid_prefix to 0.
--------------------------------------------------------------------------
nThread 1 nGpus 8 minBytes 9 maxBytes 33554432 step: 1048576(bytes) warmup iters: 5 iters: 20 validation: 1
--------------------------------------------------------------------------
A process has executed an operation involving a call to the
"fork()" system call to create a child process.  Open MPI is currently
operating in a condition that could result in memory corruption or
other system errors; your job may hang, crash, or produce silent
data corruption.  The use of fork() (or system() or other calls that
create child processes) is strongly discouraged.

The process that invoked fork was:

  Local host:          [[62619,1],1] (PID 3535)

If you are *absolutely sure* that your application will successfully
and correctly survive a call to fork(), you may disable this warning
by setting the mpi_warn_on_fork MCA parameter to 0.
--------------------------------------------------------------------------
[seedsmed-f02hpc01:03622] 1 more process has sent help message help-mpi-btl-openib.txt / default subnet prefix
[seedsmed-f02hpc01:03622] Set MCA parameter "orte_base_help_aggregate" to 0 to see all help / error messages
[seedsmed-f02hpc01:03622] 1 more process has sent help message help-opal-runtime.txt / opal_init:warn-fork
# NCCL Tests compiled with NCCL 2.1
# Using devices
#   Rank  0 on seedsmed-f02hpc01 device  0 [0x04] Tesla V100-PCIE-16GB
#   Rank  1 on seedsmed-f02hpc01 device  1 [0x06] Tesla V100-PCIE-16GB
#   Rank  2 on seedsmed-f02hpc01 device  2 [0x07] Tesla V100-PCIE-16GB
#   Rank  3 on seedsmed-f02hpc01 device  3 [0x08] Tesla V100-PCIE-16GB
#   Rank  4 on seedsmed-f02hpc01 device  4 [0x0c] Tesla V100-PCIE-16GB
#   Rank  5 on seedsmed-f02hpc01 device  5 [0x0d] Tesla V100-PCIE-16GB
#   Rank  6 on seedsmed-f02hpc01 device  6 [0x0e] Tesla V100-PCIE-16GB
#   Rank  7 on seedsmed-f02hpc01 device  7 [0x0f] Tesla V100-PCIE-16GB
#   Rank  8 on seedsmed-f02hpc02 device  0 [0x04] Tesla V100-PCIE-16GB
#   Rank  9 on seedsmed-f02hpc02 device  1 [0x06] Tesla V100-PCIE-16GB
#   Rank 10 on seedsmed-f02hpc02 device  2 [0x07] Tesla V100-PCIE-16GB
#   Rank 11 on seedsmed-f02hpc02 device  3 [0x08] Tesla V100-PCIE-16GB
#   Rank 12 on seedsmed-f02hpc02 device  4 [0x0c] Tesla V100-PCIE-16GB
#   Rank 13 on seedsmed-f02hpc02 device  5 [0x0d] Tesla V100-PCIE-16GB
#   Rank 14 on seedsmed-f02hpc02 device  6 [0x0e] Tesla V100-PCIE-16GB

#                                                 out-of-place                    in-place
#      bytes             N    type      op     time  algbw  busbw      res     time  algbw  busbw      res
#   Rank 15 on seedsmed-f02hpc02 device  7 [0x0f] Tesla V100-PCIE-16GB
           8             2   float     sum    0.445   0.00   0.00    1e-06    0.106   0.00   0.00    0e+00
     1048584        262146   float     sum    0.624   1.68   3.15    1e+01    0.624   1.68   3.15    1e+01
     2097160        524290   float     sum    1.026   2.04   3.83    1e+01    1.019   2.06   3.86    1e+01
     3145736        786434   float     sum    1.359   2.31   4.34    1e+01    1.358   2.32   4.34    1e+01
     4194312       1048578   float     sum    1.732   2.42   4.54    1e+01    1.728   2.43   4.55    1e+01
     5242888       1310722   float     sum    2.070   2.53   4.75    1e+01    2.078   2.52   4.73    1e+01
     6291464       1572866   float     sum    2.447   2.57   4.82    1e+01    2.445   2.57   4.82    1e+01
     7340040       1835010   float     sum    2.794   2.63   4.93    1e+01    2.798   2.62   4.92    1e+01
     8388616       2097154   float     sum    3.165   2.65   4.97    1e+01    3.168   2.65   4.97    1e+01
     9437192       2359298   float     sum    3.529   2.67   5.01    1e+01    3.526   2.68   5.02    1e+01
    10485768       2621442   float     sum    3.918   2.68   5.02    1e+01    3.938   2.66   4.99    1e+01
    11534344       2883586   float     sum    4.308   2.68   5.02    1e+01    4.308   2.68   5.02    1e+01
    12582920       3145730   float     sum    4.682   2.69   5.04    1e+01    4.718   2.67   5.00    1e+01
    13631496       3407874   float     sum    5.051   2.70   5.06    1e+01    5.065   2.69   5.05    1e+01
    14680072       3670018   float     sum    5.455   2.69   5.05    1e+01    5.462   2.69   5.04    1e+01
    15728648       3932162   float     sum    5.864   2.68   5.03    1e+01    5.841   2.69   5.05    1e+01
    16777224       4194306   float     sum    6.239   2.69   5.04    1e+01    6.228   2.69   5.05    1e+01
    17825800       4456450   float     sum    6.612   2.70   5.06    1e+01    6.631   2.69   5.04    1e+01
    18874376       4718594   float     sum    7.052   2.68   5.02    1e+01    7.022   2.69   5.04    1e+01
    19922952       4980738   float     sum    7.419   2.69   5.03    1e+01    7.420   2.69   5.03    1e+01
    20971528       5242882   float     sum    7.826   2.68   5.02    1e+01    7.811   2.68   5.03    1e+01
    22020104       5505026   float     sum    8.214   2.68   5.03    1e+01    8.182   2.69   5.05    1e+01
    23068680       5767170   float     sum    8.629   2.67   5.01    1e+01    8.590   2.69   5.04    1e+01
    24117256       6029314   float     sum    9.007   2.68   5.02    1e+01    8.979   2.69   5.04    1e+01
    25165832       6291458   float     sum    9.368   2.69   5.04    1e+01    9.441   2.67   5.00    1e+01
    26214408       6553602   float     sum    9.750   2.69   5.04    1e+01    9.749   2.69   5.04    1e+01
    27262984       6815746   float     sum   10.181   2.68   5.02    1e+01   10.150   2.69   5.04    1e+01
    28311560       7077890   float     sum   10.546   2.68   5.03    1e+01   10.535   2.69   5.04    1e+01
    29360136       7340034   float     sum   10.940   2.68   5.03    1e+01   10.944   2.68   5.03    1e+01
    30408712       7602178   float     sum   11.317   2.69   5.04    1e+01   11.296   2.69   5.05    1e+01
    31457288       7864322   float     sum   11.695   2.69   5.04    1e+01   11.688   2.69   5.05    1e+01
    32505864       8126466   float     sum   12.052   2.70   5.06    1e+01   12.092   2.69   5.04    1e+01
 Out of bounds values : 248 FAILED
 Avg bus bandwidth    : 4.72189

-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[62619,1],1]
  Exit code:    1
--------------------------------------------------------------------------

**Comment by sjeaugey** [comment]
Hi, can you confirm which driver version you are using ? Also, see my comment on #8.

**Comment by wm10240** [comment]
Thanking your reply, The GPU is tesla V100，and driver is 390.46, become we must use the cuda9.1, so I don't change the version to 384(the version of cuda in 384 is 9.0), I want to know In driver 390.36, if nccl-test is not applicable？

**Comment by sjeaugey** [comment]
Driver version 384 would indeed not work with CUDA 9.1, but you can use the 387 version which should work with 9.1 and is not affected by the issue.

**Comment by AddyLaddy** [comment]
No further feedback so I'll close this issue. Please open another one if you are still seeing issues.
