### ISSUE TITLE
Question about why measurement of time for performance benchmarks includes time taken for MPI_Barrier to complete.

### ISSUE THREAD

**Issue by nithintsk** [NVIDIA/nccl-tests#72]
In the nccl performance benchmarks, the calculation of time taken by a collective call includes the time taken by MPI_Barrier in the case of blocking mode. I would like to know why this barrier is included when calculating the time? Is the presence of a barrier here even necessary? If it was removed, would it lead to any validation issues? Ideally, wouldn't we want to consider the time when a rank finishes its allreduce and obtains the value in recvbuff, instead of waiting for all other ranks to finish?
```
  auto start = std::chrono::high_resolution_clock::now();
  for (int iter = 0; iter < iters; iter++) {
    if (agg_iters>1) NCCLCHECK(ncclGroupStart());
    for (int aiter = 0; aiter < agg_iters; aiter++) {
      TESTCHECK(startColl(args, type, op, root, in_place, iter*agg_iters+aiter));
    }
    if (agg_iters>1) NCCLCHECK(ncclGroupEnd());
  }
  TESTCHECK(completeColl(args));
  auto delta = std::chrono::high_resolution_clock::now() - start;
  double deltaSec = std::chrono::duration_cast<std::chrono::duration<double>>(delta).count();
  deltaSec = deltaSec/(iters*agg_iters);
 ```
 startColl calls the corresponding collective, completes synchronization and then calls MPI_Barrier.

```
testResult_t startColl(struct threadArgs* args, ncclDataType_t type, ncclRedOp_t op, int root, int in_place, int iter) {
  size_t count = args->nbytes / wordSize(type);
.
.
.
    TESTCHECK(args->collTest->runColl(
          (void*)(in_place ? recvBuff + args->sendInplaceOffset*rank : sendBuff),
          (void*)(in_place ? recvBuff + args->recvInplaceOffset*rank : recvBuff),
        count, type, op, root, args->comms[i], args->streams[i]));
  }
  if (args->nGpus > 1) NCCLCHECK(ncclGroupEnd());

  if (blocking_coll) {
    // Complete op before returning
    TESTCHECK(testStreamSynchronize(args->nGpus, args->streams, args->comms));
  }
  if (blocking_coll) Barrier(args);  <----------------- Barrier called here
  return testSuccess;
}
```

**Comment by sjeaugey** [comment]
I think the goal here is to account for the desync between ranks and know when the last rank exited the operation.

For example, if you run a broadcast benchmark with the traditional pipeline/chain algorithm, each rank will receive from the previous rank and send to the next. You'll see a latency of e.g. 6us, **regardless of the number of ranks**.

But that doesn't mean it takes 6 us between the beginning of the operation until the last rank receives the data. That time is probably around 6us * nranks, which is what the blocking mode is supposed to measure.

Now surely the Barrier is adding some extra time, but again that was only meant to measure things like an end-to-end bcast time, in which case the barrier time would account for very little. And if the goal is just to measure the time + CUDA sync, then indeed we shouldn't count the barrier time.

**Comment by hashmij** [comment]
@sjeaugey Thanks for the reply. We wanted to make sure that we are understanding the semantics correctly and based on your reply, a nccl call followed by stream completion would suffice for the sake of algorithm correctness, is that correct? For instance, a rank participating in an ncclAllreduce followed by cudaStreamSynchronize is guaranteed to have valid result in recvbuf? And the Barrier afterwards is only meant to avoid skews and is not required as far as the correctness of the algorithm is concerned. Please correct if I am missing something.

**Comment by sjeaugey** [comment]
It is correct that the barrier is not needed for correctness. But neither does the call to `cudaStreamSynchronize`; it's only needed to ensure we are measuring a time that is greater or equal to the operation execution time.

That's why by default, we don't call cudaStreamSynchronize after each call. A normal code would access the recvbuff using another CUDA kernel, which only needs to follow CUDA stream semantics to ensure recvbuff is valid.

**Comment by hashmij** [comment]
Thanks! This makes sense.
