### ISSUE TITLE
NCCL_HOME value in build command

### ISSUE THREAD

**Issue by jzhang82119** [NVIDIA/nccl-tests#73]
When compiling test suite below, what is value of NCCL_HOME?  I believe it is not **/usr** in my case.
make MPI=1 MPI_HOME=/usr/local/openmpi CUDA_HOME=/usr/local/cuda **NCCL_HOME=/usr**

I used the following two local packages to install nccl.
libnccl-dev_2.7.8-1+cuda11.0_amd64.deb
libnccl2_2.7.8-1+cuda11.0_amd64.deb

dpkg --contents libnccl2_2.7.8-1+cuda11.0_amd64.deb

drwxr-xr-x root/root         0 2020-07-12 16:08 ./
drwxr-xr-x root/root         0 2020-07-12 16:08 ./usr/
drwxr-xr-x root/root         0 2020-07-12 16:08 ./usr/lib/
drwxr-xr-x root/root         0 2020-07-12 16:08 ./usr/lib/x86_64-linux-gnu/
-rw-r--r-- root/root 109312912 2020-07-12 16:08 ./usr/lib/x86_64-linux-gnu/libnccl.so.2.7.8
drwxr-xr-x root/root         0 2020-07-12 16:08 ./usr/share/
drwxr-xr-x root/root         0 2020-07-12 16:08 ./usr/share/doc/
drwxr-xr-x root/root         0 2020-07-12 16:08 ./usr/share/doc/libnccl2/
-rw-r--r-- root/root       155 2020-07-12 16:08 ./usr/share/doc/libnccl2/changelog.Debian.gz
-rw-r--r-- root/root      1735 2020-07-12 16:08 ./usr/share/doc/libnccl2/copyright
lrwxrwxrwx root/root         0 2020-07-12 16:08 ./usr/lib/x86_64-linux-gnu/libnccl.so.2 -> libnccl.so.2.7.8

dpkg --contents libnccl-dev_2.7.8-1+cuda11.0_amd64.deb

drwxr-xr-x root/root         0 2020-07-12 16:08 ./
drwxr-xr-x root/root         0 2020-07-12 16:08 ./usr/
drwxr-xr-x root/root         0 2020-07-12 16:08 ./usr/include/
-rw-r--r-- root/root     12048 2020-07-12 16:08 ./usr/include/nccl.h
drwxr-xr-x root/root         0 2020-07-12 16:08 ./usr/lib/
drwxr-xr-x root/root         0 2020-07-12 16:08 ./usr/lib/x86_64-linux-gnu/
-rw-r--r-- root/root 111170908 2020-07-12 16:08 ./usr/lib/x86_64-linux-gnu/libnccl_static.a
drwxr-xr-x root/root         0 2020-07-12 16:08 ./usr/share/
drwxr-xr-x root/root         0 2020-07-12 16:08 ./usr/share/doc/
drwxr-xr-x root/root         0 2020-07-12 16:08 ./usr/share/doc/libnccl-dev/
-rw-r--r-- root/root       155 2020-07-12 16:08 ./usr/share/doc/libnccl-dev/changelog.Debian.gz
-rw-r--r-- root/root      1735 2020-07-12 16:08 ./usr/share/doc/libnccl-dev/copyright
lrwxrwxrwx root/root         0 2020-07-12 16:08 ./usr/lib/x86_64-linux-gnu/libnccl.so -> libnccl.so.2

**Comment by sjeaugey** [comment]
If NCCL is installed in /usr then you should not need to specify NCCL_HOME at all. Also note CUDA_HOME is /usr/local/cuda by default, so you should only need:
```
make -j MPI=1 MPI_HOME=/usr/local/openmpi 
```

**Comment by jzhang82119** [comment]
how do I know where NCCL is installed?  what is the NCCL program called?

**Comment by AddyLaddy** [comment]
Your dpkg commands above show where the NCCL libraries and header file have been installed. As they are installed in the standard system locations you shoud not need to set NCCL_HOME during compilation of the tests
There is no "NCCL program"
