### ISSUE TITLE
mpi.h is included by a wrong way

### ISSUE THREAD

**Issue by Co1lin** [NVIDIA/nccl-tests#75]
After installing mpich via apt on Ubuntu, I ran `make` but got an error. It said `mpi.h: No such file or directory`. After checking this issue on the Internet, I realized that in `src/common.h`, `mpi.h` should be included by `#include "mpich/mpi.h"`, rather than `#include "mpi.h"`.

I am not sure whether or not it depends on the way to install MPI. However, I think this issue should be noted in `readme.md` at least.

**Comment by AddyLaddy** [comment]
We generally build the NCCL tests against an OpenMPI release where `#include "mpi.h"` works fine. But perhaps we should add a note about MPICH.

**Comment by sjeaugey** [comment]
I'm pretty sure MPICH does not expect programs to `#include "mpich/mpi.h"`. That would be contrary to the MPI standard which intend to make an MPI program run on any implementation, be it MPICH, Open MPI, or any MPI coming from vendors like IBM, Cray, ...

Can you explain how you installed MPICH ? `mpi.h` should end up in some `include/` directory, not in an `mpich/` directory, or there should be a symlink somewhere.

**Comment by sjeaugey** [comment]
I checked on an Ubuntu MPICH package and they do have such a symlink. Can you try compiling with `MPI_HOME=/usr/lib/x86_64-linux-gnu/mpich/` ? This is similar to OpenMPI which you would use with `MPI_HOME=/usr/lib/x86_64-linux-gnu/openmpi/`.

**Comment by Co1lin** [comment]
@sjeaugey On my Ubuntu, there's no `/usr/lib/x86_64-linux-gnu/mpich`, but `/usr/lib/mpich`. Though `mpich/mpi.h` works fine for me, I've understood what you mean. Thanks for your help. ^_^
