### ISSUE TITLE
how to make all reduce use ring

### ISSUE THREAD

**Issue by Mellonta** [NVIDIA/nccl-tests#89]
Environment:
NCCL 2.8.3
Cuda 11.1
Two nodes, each of which has 8 Tesla-T4, on 100G RoCEv2.

The simplified command is 
mpirun -n 16 --npernode 8  -x NCCL_DEBUG=INFO -x NCCL_ALGO=Ring -x NCCL_MAX_NCHANNELS=1 nccl-tests/build/all_reduce_perf -n 100 -w 20 -b 8 -e 256M -f 2 -g 1

The log file:
[nccl_debug_log.txt](https://github.com/NVIDIA/nccl-tests/files/6634634/nccl_debug_log.txt)

The topology from the log is:  the number is the rank of GPU, [4n, 4n+8) belong to the same node
<pre>
[11->10->9->8]->[15->14->13->12]
                             ↓
[3->2->1->0]->[7->6->5->     4]
</pre>

doesn't seem to form a ring.

With NCCL_DEBUG_SUBSYS=TUNING, it prints:

n129-118-012:1802:1851 [0] NCCL INFO Latency/AlgBw |    Tree/    LL |    Tree/ LL128 |    Tree/Simple |    Ring/    LL |    Ring/ LL128 |    Ring/Simple | CollNet/    LL | CollNet/ LL128 | CollNet/Simple |
n129-118-012:1802:1851 [0] NCCL INFO  Max NThreads |            512 |            640 |            512 |            512 |            640 |            256 |            512 |            640 |            512 |
n129-118-012:1802:1851 [0] NCCL INFO     Broadcast |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |     6.3/   0.0 |    14.0/   0.0 |    18.0/   9.0 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
n129-118-012:1802:1851 [0] NCCL INFO        Reduce |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |     6.3/   0.0 |    14.0/   0.0 |    18.0/   9.0 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
n129-118-012:1802:1851 [0] NCCL INFO     AllGather |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |    31.5/   0.0 |    49.0/   0.0 |    97.8/   9.6 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
n129-118-012:1802:1851 [0] NCCL INFO ReduceScatter |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |    31.5/   0.0 |    49.0/   0.0 |    97.8/   9.6 |     0.0/   0.0 |     0.0/   0.0 |     0.0/   0.0 |
n129-118-012:1802:1851 [0] NCCL INFO     AllReduce |    39.6/   0.0 |    48.0/   0.0 |   448.0/   0.0 |    59.4/   0.0 |    88.0/   0.0 |   187.2/   4.8 |    22.0/   0.0 |    26.2/   0.0 |    66.7/   0.0 |

which doesn't conform with https://github.com/NVIDIA/nccl/issues/408

4 nodes:
[4nodes.txt](https://github.com/NVIDIA/nccl-tests/files/6664960/4nodes.txt)

![image](https://user-images.githubusercontent.com/8849142/122269794-9b969a80-ceab-11eb-869d-8c153eb2cbd0.png)

How can I make nccl_test use ring algorithm?

**Comment by eric-haibin-lin** [comment]
@sjeaugey could you provide some suggestions on why this happens on how to debug it?

**Comment by kwen2501** [comment]
To force NCCL to use the Ring algorithm, you can simply set `NCCL_ALGO=Ring`, see https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-algo

The formed ring is represented by this line in your log:

You have a difference tuning matrix than the one in #408 likely because you have a different machine. That is, NCCL determines the tuning matrix based on auto-detection on the machine.

**Comment by Mellonta** [comment]
@kwen2501 Do you mean that NCCL always runs a detection algorithm even if the user set the algorithm? I'm confused because @sjeaugey said 

> If you set NCCL_DEBUG_SUBSYS=TUNING you should see all proto/algo combinations have a bandwidth of 0, except Ring/Simple.

**Comment by kwen2501** [comment]
Yes, NCCL always run the (intra-node topology) detection no matter which algorithm the user sets.

I do see all columns showing a bandwidth of 0 except Ring/Simple. The way to read the matrix items is "latency / algorithm bandwidth".

**Comment by Mellonta** [comment]
@kwen2501 Got it, thank you!
