### ISSUE TITLE
mpi run on multi nodes does not work

### ISSUE THREAD

**Issue by gmyofustc** [NVIDIA/nccl-tests#9]
hi，
    I build nccl test with nccl2.1, I can run the test on one node, when i run it on 2 node , it just gets stuck like this 
![image](https://user-images.githubusercontent.com/7859276/40247081-c4739e64-5afd-11e8-8bfd-396a04877d41.png)
 any help, thanks a lot

**Comment by sjeaugey** [comment]
You might want to make sure NCCL is using a network interface which can communicate between the two nodes, e.g. :
`mpirun -np 2 -f hostfile -x NCCL_SOCKET_IFNAME=eth0 ./build/...`

You can also review the "Knobs" section of the documentation about NCCL_SOCKET_IFNAME.

**Comment by zrss** [comment]
`NCCL_SOCKET_IFNAME` seems a prefix match ... if u unluckily has those NIC in a node

```
bond0

bond0.2093

bond0.2093.1 (this network space can't be used for comm)
```

wdyt ? how do u solve this case

**Comment by sjeaugey** [comment]
Indeed, we're aware of the potential limitation of using prefixes.
In you case though, `NCCL_SOCKET_IFNAME=^bond0.2093` might work.

**Comment by AddyLaddy** [comment]
We now support exact interface name matching in NCCL using the `==` syntax.
