### ISSUE TITLE
testing nccl in 2 nodes and 16 gpus and something wrong

### ISSUE THREAD

**Issue by ngc7292** [NVIDIA/nccl-tests#98]
we use this to test 2 nodes and each node have 8 gpus and use command

```
sudo env LD_LIBRARY_PATH=$LD_LIBRARY_PATH NCCL_DEBUG=DEBUG /usr/local/openmpi/bin/mpirun --allow-run-as-root -np $((MA_NUM_HOSTS*8)) -hostfile /home/ma-user/mpihost.txt -mca plm_rsh_args "-p 2222" -bind-to none -map-by slot -x NCCL_DEBUG=INFO ./build/all_reduce_perf -b 8 -e 512M
```

and get some wrong

` Test CUDA failure common.cu:1045 'CUDA driver version is insufficient for CUDA runtime version'`

nvcc and nvidia-smi output

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:07:16_PDT_2019
Cuda compilation tools, release 10.1, V10.1.243
NVRM version: NVIDIA UNIX x86_64 Kernel Module  440.33.01  Wed Nov 13 00:00:22 UTC 2019
GCC version:  gcc version 4.8.5 20150623 (EulerOS 4.8.5-28) (GCC) 
```

**Comment by sjeaugey** [comment]
Can you check the version of NCCL you are using?

**Comment by ngc7292** [comment]
in  nccl.h  i get

```
#define NCCL_MAJOR 2
#define NCCL_MINOR 8
#define NCCL_PATCH 3
#define NCCL_SUFFIX ""

#define NCCL_VERSION_CODE 2803
```

but i'm not sure  -_-?

**Comment by ngc7292** [comment]
the complie command is 

```
make MPI=1 MPI_HOME=/usr/local/openmpi/ CUDA_HOME=/usr/local/cuda NCCL_HOME=/usr/
```

**Comment by sjeaugey** [comment]
Can you run `dpkg -l | grep nccl`?

**Comment by ngc7292** [comment]
yep，we use it know nccl version is 2.8.3

**Comment by sjeaugey** [comment]
I'd like to check the NCCL version is compiled against the right version of CUDA. `dpkg` would give you the full package name, e.g. 2.8.3-1+cuda10.0. Alternatively, you can run `ldd ./build/all_reduce_perf` then `strings /path/to/libnccl.so.2.8 | grep -i version`.

**Comment by AddyLaddy** [comment]
You should also be careful to make sure that the LD_LIBRARY_PATH is the same in each rank. `mpirun` does not forward any environment variables unless you explicitly ask it i.e. add `-x LD_LIBRARY_PATH` in your command line above.

**Comment by ngc7292** [comment]
> I'd like to check the NCCL version is compiled against the right version of CUDA. `dpkg` would give you the full package name, e.g. 2.8.3-1+cuda10.0. Alternatively, you can run `ldd ./build/all_reduce_perf` then `strings /path/to/libnccl.so.2.8 | grep -i version`.

dpkg reply version is 
```
hi  libnccl-dev                            2.8.3-1+cuda10.1                       amd64        NVIDIA Collective Communication Library (NCCL) Development Files
hi  libnccl2                               2.8.3-1+cuda10.1                       amd64        NVIDIA Collective Communication Library (NCCL) Runtime
ii  nccl-repo-ubuntu1804-2.8.3-ga-cuda10.1 1-1
```

**Comment by ngc7292** [comment]
> You should also be careful to make sure that the LD_LIBRARY_PATH is the same in each rank. `mpirun` does not forward any environment variables unless you explicitly ask it i.e. add `-x LD_LIBRARY_PATH` in your command line above.

wow , it's work !   thank you !!!
